"""initial schema

Revision ID: bb47bceb8cdd
Revises: 
Create Date: 2026-08-13 18:34:58.048384

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.core.types  # custom types (GUID) — kein Rename ohne Migration


# revision identifiers, used by Alembic.
revision: str = 'bb47bceb8cdd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('project_id', app.core.types.GUID(), nullable=True),
    sa.Column('nvt_id', app.core.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ruleset_version', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_nvt_id'), ['nvt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('projects',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_label', sa.String(length=200), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('client', sa.String(length=200), nullable=True),
    sa.Column('contractor', sa.String(length=200), nullable=False),
    sa.Column('site_manager_name', sa.String(length=200), nullable=True),
    sa.Column('on_site_responsible_name', sa.String(length=200), nullable=True),
    sa.Column('on_site_responsible_phone', sa.String(length=50), nullable=True),
    sa.Column('ruleset_version', sa.String(length=20), nullable=False),
    sa.Column('vision_provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exports',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('project_id', app.core.types.GUID(), nullable=False),
    sa.Column('docx_path', sa.String(length=500), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('included_nvt_ids', sa.JSON(), nullable=False),
    sa.Column('qa_gate_report', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_project_id'), ['project_id'], unique=False)

    op.create_table('nvts',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('project_id', app.core.types.GUID(), nullable=False),
    sa.Column('nvt_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('address_json', sa.JSON(), nullable=True),
    sa.Column('location_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('duplicates_of', app.core.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['duplicates_of'], ['nvts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'nvt_number', name='uq_nvt_per_project')
    )
    with op.batch_alter_table('nvts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nvts_nvt_number'), ['nvt_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_nvts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nvts_status'), ['status'], unique=False)

    op.create_table('decisions',
    sa.Column('nvt_id', app.core.types.GUID(), nullable=False),
    sa.Column('selected_ruleplan_id', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('vision_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('rule_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('data_completeness', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=20), nullable=False),
    sa.Column('ruleplan_revision_hash', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('trace_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nvt_id'], ['nvts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nvt_id')
    )
    op.create_table('environment_analyses',
    sa.Column('nvt_id', app.core.types.GUID(), nullable=False),
    sa.Column('road_present', sa.String(length=10), nullable=False),
    sa.Column('sidewalk_present', sa.String(length=10), nullable=False),
    sa.Column('cycleway_present', sa.String(length=10), nullable=False),
    sa.Column('shared_cycle_footway_present', sa.String(length=10), nullable=False),
    sa.Column('parking_lane_present', sa.String(length=10), nullable=False),
    sa.Column('seiten_streifen_present', sa.String(length=10), nullable=False),
    sa.Column('private_property', sa.String(length=10), nullable=False),
    sa.Column('business_property', sa.String(length=10), nullable=False),
    sa.Column('driveway_present', sa.String(length=10), nullable=False),
    sa.Column('intersection_present', sa.String(length=10), nullable=False),
    sa.Column('junction_present', sa.String(length=10), nullable=False),
    sa.Column('cul_de_sac', sa.String(length=10), nullable=False),
    sa.Column('curve_present', sa.String(length=10), nullable=False),
    sa.Column('bus_stop_nearby', sa.String(length=10), nullable=False),
    sa.Column('fire_access', sa.String(length=10), nullable=False),
    sa.Column('nvt_position', sa.String(length=30), nullable=False),
    sa.Column('road_class', sa.String(length=20), nullable=False),
    sa.Column('sidewalk_width_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('roadway_width_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cycleway_width_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('distance_nvt_to_road_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('parked_vehicles_in_workarea', sa.String(length=10), nullable=False),
    sa.Column('existing_signs', sa.JSON(), nullable=False),
    sa.Column('existing_barriers', sa.JSON(), nullable=False),
    sa.Column('obstacles', sa.JSON(), nullable=False),
    sa.Column('sight_relations_affected', sa.String(length=10), nullable=False),
    sa.Column('contributing_photos', sa.JSON(), nullable=False),
    sa.Column('vision_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('data_completeness', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('contradictions', sa.JSON(), nullable=False),
    sa.Column('raw_provider_output', sa.JSON(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nvt_id'], ['nvts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nvt_id')
    )
    op.create_table('photos',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('nvt_id', app.core.types.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('exif', sa.JSON(), nullable=False),
    sa.Column('ocr_json', sa.JSON(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nvt_id'], ['nvts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_nvt_id'), ['nvt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_sha256'), ['sha256'], unique=False)

    op.create_table('reviews',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('nvt_id', app.core.types.GUID(), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nvt_id'], ['nvts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_nvt_id'), ['nvt_id'], unique=False)

    op.create_table('ruleplan_candidates',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('nvt_id', app.core.types.GUID(), nullable=False),
    sa.Column('ruleplan_id', sa.String(length=20), nullable=False),
    sa.Column('matched_predicates', sa.JSON(), nullable=False),
    sa.Column('unmet_requirements', sa.JSON(), nullable=False),
    sa.Column('triggered_exclusions', sa.JSON(), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['nvt_id'], ['nvts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ruleplan_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruleplan_candidates_nvt_id'), ['nvt_id'], unique=False)

    op.create_table('traffic_user_assessments',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('nvt_id', app.core.types.GUID(), nullable=False),
    sa.Column('user', sa.String(length=30), nullable=False),
    sa.Column('affected', sa.Boolean(), nullable=False),
    sa.Column('current_route', sa.Text(), nullable=True),
    sa.Column('proposed_route', sa.Text(), nullable=True),
    sa.Column('safe', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['nvt_id'], ['nvts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nvt_id', 'user', name='uq_traffic_user')
    )
    with op.batch_alter_table('traffic_user_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_user_assessments_nvt_id'), ['nvt_id'], unique=False)

    op.create_table('work_areas',
    sa.Column('nvt_id', app.core.types.GUID(), nullable=False),
    sa.Column('bulli_position', sa.JSON(), nullable=True),
    sa.Column('bulli_length_m', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('bulli_width_m', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('equipment_position', sa.JSON(), nullable=True),
    sa.Column('barrier_polygon', sa.JSON(), nullable=False),
    sa.Column('required_traffic_area', sa.String(length=40), nullable=False),
    sa.Column('affects_sidewalk', sa.Boolean(), nullable=False),
    sa.Column('affects_road', sa.Boolean(), nullable=False),
    sa.Column('affects_cycleway', sa.Boolean(), nullable=False),
    sa.Column('affects_driveway', sa.Boolean(), nullable=False),
    sa.Column('affects_bus_stop', sa.Boolean(), nullable=False),
    sa.Column('remaining_roadway_width_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remaining_sidewalk_width_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nvt_id'], ['nvts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nvt_id')
    )
    op.create_table('visualizations',
    sa.Column('nvt_id', app.core.types.GUID(), nullable=False),
    sa.Column('base_photo_id', app.core.types.GUID(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('shapes', sa.JSON(), nullable=False),
    sa.Column('rendered_photo_id', app.core.types.GUID(), nullable=True),
    sa.Column('final_photo_id', app.core.types.GUID(), nullable=True),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['base_photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['final_photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['nvt_id'], ['nvts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rendered_photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('nvt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visualizations')
    op.drop_table('work_areas')
    with op.batch_alter_table('traffic_user_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_user_assessments_nvt_id'))

    op.drop_table('traffic_user_assessments')
    with op.batch_alter_table('ruleplan_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruleplan_candidates_nvt_id'))

    op.drop_table('ruleplan_candidates')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_nvt_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_sha256'))
        batch_op.drop_index(batch_op.f('ix_photos_nvt_id'))

    op.drop_table('photos')
    op.drop_table('environment_analyses')
    op.drop_table('decisions')
    with op.batch_alter_table('nvts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nvts_status'))
        batch_op.drop_index(batch_op.f('ix_nvts_project_id'))
        batch_op.drop_index(batch_op.f('ix_nvts_nvt_number'))

    op.drop_table('nvts')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_project_id'))

    op.drop_table('exports')
    op.drop_table('projects')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_nvt_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
